name: pinet
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/pihedron/pinet

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.4.0
  dotenv: ^4.2.0
  http: ^1.2.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  timeago: ^3.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
